import { createClient } from "@supabase/supabase-js";
const supabase = createClient("https://qzwnnjocnmihedenphub.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6d25uam9jbm1paGVkZW5waHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTgwMDM0NTMsImV4cCI6MjAxMzU3OTQ1M30.tKoRyEXvfGd9Cmnh1s9YtGkHhYKXw8fC9ewsmjFmEy0")
export default supabase